# Generated by Django 5.1.6 on 2025-02-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EFOTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ontology_id', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('iri', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EFOSynonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonym', models.CharField(max_length=255, unique=True)),
                ('terms', models.ManyToManyField(related_name='synonyms', to='efo.efoterm')),
            ],
        ),
    ]
