# Generated by Django 5.1.6 on 2025-02-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efo', '0002_alter_efosynonym_synonym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efoterm',
            name='label',
            field=models.CharField(max_length=1024),
        ),
    ]
