# Generated by Django 5.1.6 on 2025-02-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efo', '0003_alter_efoterm_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='efoterm',
            name='has_children',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='efoterm',
            name='is_obsolete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='efoterm',
            name='is_root',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='efoterm',
            name='lang',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='efoterm',
            name='obo_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
